version: '3.8'

services:
  web:
    image: ece651foodie.azurecr.io/ece651_web
    ports:
      - 8000:8000
    volumes:
      - static_volume:/home/app/backend/backend/staticfiles
  nginx:
    image: ece651foodie.azurecr.io/ece651_nginx
    ports:
      - 80:80
    depends_on:
      - web
    volumes:
      - static_volume:/home/app/backend/backend/staticfiles
volumes:
  static_volume: