version: '3.8'

services:
  web:
    image: ece651foodie.azurecr.io/ece651_web:latest
    volumes:
      - static_volume:/home/app/backend_project/staticfiles
    environment:
      DB_HOST: "google.com:3306"
      DB_USER: "wordpress"
      DB_PASSWORD: "wordpress"
  nginx:
    image: ece651foodie.azurecr.io/ece651_nginx:latest
    ports:
      - 80:80
      - 2222:2222
    volumes:
      - static_volume:/home/app/backend_project/staticfiles
volumes:
  static_volume: