version: '3.8'

services:
  web:
    image: ece651foodie.azurecr.io/ece651_web
    expose:
      - 8000
    env_file:
      - ./env.prod
    volumes:
      - static_volume:/home/app/backend/backend/staticfiles
  nginx:
    image: ece651foodie.azurecr.io/ece651_nginx
    ports:
      - 80:80
    depends_on:
      - web
    volumes:
      - static_volume:/home/app/backend/backend/staticfiles

volumes:
  static_volume: