version: '3.8'

services:
  web:
    image: ece651foodie.azurecr.io/ece651_web:latest
    volumes:
      - static_volume:/home/app/backend/staticfiles
    environment:
      DB_HOST: "google.com:3306"
      DB_USER: "wordpress"
      DB_PASSWORD: "wordpress"
  nginx:
    image: ece651foodie.azurecr.io/ece651_nginx:latest
    ports:
      - 80:80
    volumes:
      - static_volume:/home/app/backend/staticfiles
volumes:
  static_volume: