version: '3.8'

services:
  web:
    build: ./
    command: bash -c "python backend_project/manage.py collectstatic --no-input --clear && gunicorn backend.wsgi:application --bind 0.0.0.0:8000 --pythonpath './backend_project/'"
    expose:
      - 8000
    env_file:
      - ./env.prod
    volumes:
      - static_volume:/home/app/backend/backend/staticfiles
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
    volumes:
      - static_volume:/home/app/backend/backend/staticfiles

volumes:
  static_volume: