# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ece651-foodie

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://ece651foodie.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_53746dbef1fb44f585621ca2289898c8 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_69f3a7e96e3548e8baeadc6df7dc2ca7 }}

    - name: Build and push gunicorn container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ece651foodie.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_53746dbef1fb44f585621ca2289898c8 }}/ece651_web:${{ github.sha }}
        file: ./Dockerfile

    - name: Build and push nginx container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ece651foodie.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_53746dbef1fb44f585621ca2289898c8 }}/ece651_nginx:${{ github.sha }}
        file: ./nginx/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - uses: actions/checkout@v2
    
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - run: |
        az webapp list
        ls -lah
        pwd
    
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2.2.3
      with:
        app-name: 'ece651-foodie'
        slot-name: 'production'
        configuration-file: './docker-compose.yml'
        images: |
          'ece651foodie.azurecr.io/ece651_web:latest'
          'ece651foodie.azurecr.io/ece651_nginx:latest'
        
